DEPARTMENT_ROLES = {
    "Engineering": [
        "Software Engineer",
        "Senior Software Engineer",
        "Backend Engineer",
        "Frontend Engineer",
        "Full Stack Engineer",
        "DevOps Engineer",
        "QA Engineer",
        "Technical Lead",
        "Engineering Manager",
    ],
    "Product": ["Product Manager", "Senior Product Manager", "Product Analyst"],
    "Design": ["UX Designer", "UI Designer", "Product Designer"],
    "Data": ["Data Scientist", "Data Engineer", "Data Analyst", "ML Engineer"],
    "HR": ["HR Manager", "HR Specialist", "Recruiter", "HR Business Partner"],
    "Finance": ["Finance Analyst", "Senior Finance Analyst", "Controller"],
    "Marketing": ["Marketing Manager", "Content Strategist", "Growth Manager"],
    "Sales": ["Sales Representative", "Account Executive", "Sales Manager"],
    "Operations": ["Operations Manager", "Business Analyst", "Project Manager"],
    "Legal": ["Legal Counsel", "Paralegal", "Compliance Manager"],
    "Security": ["Security Engineer", "Security Analyst"],
    "Customer Success": ["Customer Success Manager", "Support Specialist"],
}

COUNTRIES = [
    "USA",
    "India",
    "UK",
    "Canada",
    "Germany",
    "France",
    "Australia",
    "Brazil",
    "Netherlands",
    "Singapore",
    "Japan",
    "Spain",
    "Sweden",
    "Poland",
    "Mexico",
    "Italy",
    "South Korea",
    "Switzerland",
    "UAE",
    "Portugal",
]
