# Generated by Django 6.0.5 on 2026-05-25 03:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_add_salary_check_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Old Salary of the employee in USD",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "new_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="New Salary of the employee in USD",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Note for the audit", null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="employee",
            name="salary_min_1",
        ),
        migrations.AddField(
            model_name="employeeaudit",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audits",
                to="employees.employee",
            ),
        ),
    ]
